name: portolink_admin
version: 2.0+2
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  animated_theme_switcher: ^2.0.6
  cloud_firestore: ^3.1.13
  connectivity_plus: ^2.3.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  firebase_messaging: ^11.2.15
  firebase_storage: ^10.2.14
  flutter_lints: ^1.0.4
  flutter_profile_picture: ^1.0.2
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  lottie: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
    - family: Flamenco
      fonts:
        - asset: assets/fonts/Flamenco-Regular.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf